name: Cypress Tests CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        # Add more browsers as needed
        container: [cypress/browsers:node-18.16.0-chrome-114.0.5735.90-1-ff-115.0.2-edge-114.0.1823.37-1]
    
    container:
      image: cypress/browsers:node-18.16.0-chrome-114.0.5735.90-1-ff-115.0.2-edge-114.0.1823.37-1
      options: --user 1001
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: chrome
          headless: true
          start: npm start # Adjust based on your app
          wait-on: 'http://localhost:3000' # Adjust based on your app
          wait-on-timeout: 120
      
      - name: Generate Test Report
        if: always()
        run: |
          npm run merge:reports || true
          npm run generate:report || true
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results-${{ matrix.container }}
          path: |
            cypress/screenshots
            cypress/videos
            cypress/reports
          retention-days: 30
      
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: cypress/reports/html
          retention-days: 7

