name: Cypress Visual Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run visual tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Visual Tests
        run: npm run test:visual
        env:
          CYPRESS_TAGS: visual,screenshot

      - name: Upload Visual Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-visual-reports
          path: cypress/reports/
          retention-days: 30

      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots/
          retention-days: 30
